from collections.abc import Iterable
from typing import Any

__all__ = ['QRNG']

class QRNG:
    def __init__(self) -> None: ...
    def randint(self, lowerbound: int, upperbound: int) -> int: ...
    def randbin(self) -> bool: ...
    def random(self, num_digits: int) -> float: ...
    def choice(self, items: Iterable[Any]) -> Any: ...
    def choices(self, items: Iterable[Any], num_selections: int) -> Any | list[Any]: ...
    def sample(self, items: Iterable[Any], num_selections: int) -> Any | list[Any]: ...
    def shuffle(self, items: Iterable[Any]) -> list[Any]: ...
